table ChartConfig
	isHidden
	lineageTag: b64ea08a-c524-49f6-91ea-4bd766412599

	column SplitBy
		dataType: string
		isHidden
		lineageTag: 4be077cd-3a54-4b74-b416-fd89cc5db07d
		summarizeBy: none
		sourceColumn: SplitBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LegendBy
		dataType: string
		isHidden
		lineageTag: d7bc690d-7e79-4686-b8eb-189b3f6f0d9e
		summarizeBy: none
		sourceColumn: LegendBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SortKey
		dataType: string
		isHidden
		lineageTag: a1326531-1283-4e25-bcac-04374e973d7d
		summarizeBy: none
		sourceColumn: SortKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Configuration
		dataType: string
		isHidden
		lineageTag: 5965f74b-d71e-49bb-a17a-56800c4c1d79
		summarizeBy: none
		sourceColumn: Configuration
		sortByColumn: SortKey

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition ChartConfig = m
		mode: import
		queryGroup: 'Inputs and Config Tables'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlDSUQouyMksUUiqtFLIy89LtVZwzs/JLwLzSxLTgfIgUSAVkpjul5ibqhSrE61kiKINogwmD9UQGwsA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [SortKey = _t, Configuration = _t, SplitBy = _t, LegendBy = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"SplitBy", type text}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

