table 'Time Series Core'
	lineageTag: ca8dd070-6b8e-438b-a4f4-b3dc1c88e14a

	measure 'Chart Title' =
			
			VAR tagCount = COUNTROWS(Tags)
			RETURN "Observations " & IF(SELECTEDVALUE(ChartConfig[SplitBy]) = "tag", "and anomalies ", "") & "for " & IF(tagCount>1, tagCount & " tags", SELECTEDVALUE(Tags[TagName]))
		lineageTag: 6264ec8f-b8e3-4686-872d-a64239e70d9f

	column TagName
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: d1a591ef-f1c0-43bd-815c-a11d361d59bc
		summarizeBy: none
		sourceColumn: TagName

		annotation SummarizationSetBy = Automatic

	column Tag
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: d687fa54-6b07-4206-ab5a-3c62fc7250c7
		summarizeBy: none
		sourceColumn: Tag

		annotation SummarizationSetBy = Automatic

	column color
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: c76bfc18-d0ee-4fab-a528-2f01f672aa1a
		summarizeBy: none
		sourceColumn: color

		annotation SummarizationSetBy = Automatic

	column Timestamp
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetimeoffset
		lineageTag: 524f5d02-7e94-470e-a81b-df6dc7cf939f
		summarizeBy: none
		sourceColumn: Timestamp

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		sourceProviderType: double
		lineageTag: b2c96686-cec6-4ad4-9cc9-d95e369a6b46
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Anomaly
		dataType: double
		sourceProviderType: double
		lineageTag: 0388711d-8565-4e9d-9193-31a117c400aa
		summarizeBy: sum
		sourceColumn: Anomaly

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Anomaly_indicator
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: a1b4e589-2039-4910-b6f5-7e31640851ce
		summarizeBy: none
		sourceColumn: Anomaly_indicator

		annotation SummarizationSetBy = Automatic

	column Level1
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 02488dd4-11b6-464b-b4e8-666cbb62491f
		summarizeBy: none
		sourceColumn: Level1

		annotation SummarizationSetBy = Automatic

	column Level2
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: eac89db6-4747-4576-9963-b44011cbf543
		summarizeBy: none
		sourceColumn: Level2

		annotation SummarizationSetBy = Automatic

	column Level3
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 6e8d5e9c-7b9c-4bad-a057-b8e4bfb54dbf
		summarizeBy: none
		sourceColumn: Level3

		annotation SummarizationSetBy = Automatic

	column Level4
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 970fb510-9136-4be2-91cc-a54a1e647838
		summarizeBy: none
		sourceColumn: Level4

		annotation SummarizationSetBy = Automatic

	partition 'Time Series Core' = m
		mode: directQuery
		source = ```
				let
				    time_range = f_parse_time_brush_range(p_time_brush_range),
				    start = time_range[Start],
				    end = time_range[End],
				    Query = "
				    let start = todatetime('" & DateTime.ToText(start) & "');
				    let end = todatetime('" & DateTime.ToText(end) & "');
				    let bin_timespan = totimespan('" & f_bin_timespan("a - *custom*", start, end, p_preferred_bin_timespan, p_max_bins, null) & "');
				    let TSMetadata = materialize(" & p_kql_query_tag_metadata & "
				        | where TagName in (" & f_parse_tags(p_tags) & "));
				    " & p_kql_query_timeseries & "
				    | where Timestamp  between (start .. end)
				    | where Tag in (TSMetadata | project Tag)
				    | make-series Value = " & p_aggregation & "(Value) default = double(null) on Timestamp step bin_timespan by Tag 
				    | project Value = series_fill_forward(Value), Timestamp, Tag
				    | extend Anomaly = series_decompose_anomalies(Value, 1.5, -1, 'linefit')
				    | mv-expand Timestamp, Value, Anomaly
				    | project Tag, todatetime(Timestamp), todouble(Value), todouble(Anomaly)
				    | project Tag, Timestamp, Value, Anomaly = iif(Anomaly != 0, Value, double(null)), Anomaly_indicator = iif(Anomaly != 0, '●', ''), color = iif(Anomaly != 0, 'FireBrick', '')
				    | lookup kind=leftouter (TSMetadata) on Tag
				    ",
				    Source = AzureDataExplorer.Contents(p_kql_cluster, p_kql_db, Query, [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null])
				in
				    Source
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

