table RelativeTime
	isHidden
	lineageTag: b030fa30-a2fc-4c3a-bf0b-c644750bb22f

	column RelativeTime
		dataType: string
		isHidden
		lineageTag: 5cca19d9-cf62-4296-a423-0c6904b2789d
		summarizeBy: none
		sourceColumn: RelativeTime

		extendedProperty ParameterMetadata =
				{
				  "version": 2,
				  "kind": 1,
				  "selectAllValue": "__SelectAll__"
				}

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SortKey
		dataType: string
		isHidden
		lineageTag: 05316f43-33f2-431a-ba03-c07106fb418d
		summarizeBy: none
		sourceColumn: SortKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition RelativeTime = m
		mode: import
		queryGroup: 'Inputs and Config Tables'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("Pc7LDoIwEIXhVyGzJJhQoEWfpWHBRQW1NBFZ+PaemaFuv5yZ/N5Tn52yfNy3Tww5FVRSV3gagCYsK8AIjACrUAlMvChVapErpD6kEbnxZo77G2JF7pCKZQM5oRnUJGqFFpBLdBZ68Kv/5UXsyTb1X47U7Be/h/DGaHgAtYk0fZXQZBof2ZxNiP7uBw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [RelativeTime = _t, SortKey = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"RelativeTime", type text}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

